weight : "./checkpoints/yolov5l.pt"
cfg : "./QAT/models/yolov5l.yaml"
data : "./dataset/coco.yaml"
hyp : "./dataset/hyps/hyp.scratch-low.yaml"
epochs : 300
batch_size : 64
imgsz : 640
rect : False
resume : False
nosave : False
noval : False
noautoanchor : False
noplots : True
#evolve : 
bucket : ""
#cache : 
image_weights : False
device : "0,1"
multi_scale : False
single_cls : False
optimizer : "SGD"
sync_bn : False
workers : 8
project : "./QAT/runs/quant_train"
name : "exp"
exist_ok : False
quad : False
cos_lr : False
label_smoothing : 0.0
patience : 100
freeze : [0]
save_period : -1
local_rank : -1
entity : None
upload_bucket : False
bbox_interval : -1
artifact_alias : "latest"
